### ISSUE TITLE
icon crashes with latest kitty version.

### ISSUE THREAD

**Issue by piuvas** [rose-pine/kitty#9]
> ️↪️ https://github.com/kovidgoyal/kitty/issues/6507

              Yeah that image is too large. X11 can take max 128x128 or 256x256 (depending on server config).
 
_Originally posted by @kovidgoyal in https://github.com/kovidgoyal/kitty/issues/6507#issuecomment-1657181443_

**Comment by mvllow** [comment]
Thanks for the report! Doesn't seem to be an issue on macOS so I'll add 256x256 versions when I get a free moment. Will also include a Figma link for the source.

**Comment by mvllow** [comment]
Added 256x256. Here's the source: https://www.figma.com/file/puPTa927EZuE6N9SnF4vCV/Ros%C3%A9-Pine?type=design&node-id=2292%3A202&mode=design&t=5vSzEYX6rVbxzIzk-1
